### ISSUE TITLE
Cant use ssh github URL

### ISSUE THREAD

**Issue by nmn1112** [int128/argocd-commenter#641]
**ArgoCd-Commenter Pod log says**
{"application": "argocd/adapter-instafin-dev", "url": "git@github.com:org_name/repo.git", "error": "invalid url: parse \"git@github.com:org_name/repo.git"\": first path segment in URL cannot contain colon"}

I have my argocd applications configured using ssh url, with ssh priv key
It should also use ssh github url.

**Comment by int128** [comment]
For now, argocd-commenter does not recognize a ssh URL. I will add a feature.

**Comment by nmn1112** [comment]
Is docker image updated in `argCd-commentor.yaml`

**Comment by nmn1112** [comment]
it seems to be working now with image `v1.8.0`

**Comment by nmn1112** [comment]
good to close, thanks a alot @int128

**Comment by int128** [comment]
`argocd-commenter.yaml` in https://github.com/int128/argocd-commenter/releases/tag/v1.8.0 should work.

Thank you for the contribution.
