### ISSUE TITLE
Cannot use argocd-commenter with multiple sources

### ISSUE THREAD

**Issue by bennesp** [int128/argocd-commenter#849]
ArgoCD v2.6 ships with a very nice feature that enables people to use multiple sources in a single Application.

This can come very handy when you want for example to define helm values in separate file in the Git repository, or for many other use cases. For further references, see here https://github.com/argoproj/argo-cd/blob/master/docs/proposals/multiple-sources-for-applications.md and here https://github.com/argoproj/argo-cd/pull/10432

The current implementation of argocd-commenter is using only the `.source` part of the `spec`, ignoring the `.sources` one, in this function:

https://github.com/int128/argocd-commenter/blob/d1ff3d35889d7643cb122d53717ed318b0555517/pkg/notification/comment.go#L23-L41

A workaround like using both `source` and `sources` in the Application definition (so that ArgoCD will ignore the `source` while using the `sources`, while argocd-commenter will pick the `source` and will ignore the `sources`) **won't work** because of how the status is now: instead of using `.revision`, now we have `.revisions`, so the following function will return an empty string, causing the caller to return nil and thus not creating any comment

https://github.com/int128/argocd-commenter/blob/d1ff3d35889d7643cb122d53717ed318b0555517/pkg/argocd/application.go#L10-L18

It would be great to have the new "multiple sources" feature implemented also on this project

**Comment by int128** [comment]
The new version https://github.com/int128/argocd-commenter/releases/tag/v1.15.0 supports the multiple sources feature.

**Comment by bennesp** [comment]
Awesome, thank you!
